---
version: "2.1"
services:
  # qBittorrent - an open-source software alternative to µTorrent.
  # Flood - a modern webUI for various torrent clients.

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ./storage:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  flood:
    image: jesec/flood
    container_name: flood
    environment:
      - HOME=/config
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./storage:/data
    ports:
      - 8081:3001
    depends_on:
      - qbittorrent
    command: --port 3001 --allowedpath /data
    restart: unless-stopped
