---
version: "2.1"
services:
  # SONARR - PVR for Usenet and BitTorrent users.
  # RADARR - a fork of Sonarr to work with movies like Couchpotato.
  # BAZARR - companion app to Sonarr/Radarr that manages and downloads subtitles.
  # JACKETT - API support for your favorite torrent trackers.

  # Documentation and useful links:
  # - https://wiki.servarr.com/docker-guide#Consistent_and_well_planned_paths

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./sonarr:/config
      - ./storage:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  # radarr:
  #   image: ghcr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Rome
  #   volumes:
  #     - ./radarr:/config
  #     - ./storage:/data
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped

  # bazarr:
  #   image: ghcr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Rome
  #   volumes:
  #     - ./bazarr:/config
  #     - ./storage:/data
  #   ports:
  #     - 6767:6767
  #   restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true  # optional
      - TZ=Europe/Rome
    volumes:
      - ./jackett:/config
      - ./storage:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
