---
version: "2.1"
services:
  # Paperless-ng
  # Scan, index and archive all your physical documents.

  paperless:
    image: lscr.io/linuxserver/paperless-ng:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - REDIS_URL=  # optional
    volumes:
      - ./config:/config
      - ./storage:/data
    ports:
      - 8000:8000
    restart: unless-stopped
