---
version: "2.1"
services:
  # Gotify - A simple server for sending and receiving messages
  # in real-time per WebSocket.

  gotify:
    # image: gotify/server-arm7:latest
    image: gotify/server:latest
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
      - TZ=Europe/Rome
    volumes:
      - ./config:/app/data
    ports:
      - 8888:80
    restart: unless-stopped
