---
version: "2.1"
services:
  # Grafana
  # The open source analytics & monitoring solution for every database.

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - grdata:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  grdata:
