---
version: "2.1"
services:
  # Nextcloud
  # The self-hosted productivity platform that keeps you in control.

  web:
    image: ghcr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
      - ./storage:/data
    ports:
      - 443:443
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
