---
version: "2.1"
services:
  # Paperless-ngx: community-supported supercharged version of paperless.
  # Scan, index and archive all your physical documents.

  paperless:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - REDIS_URL=  # optional
    volumes:
      - ./config:/config
      - ./storage:/data
    ports:
      - 8000:8000
    restart: unless-stopped
