---
version: "2.1"
services:
  # Jellyfin
  # Free media server for personal streaming.

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
      - ./media:/data
      - /opt/vc/lib:/opt/vc/lib  # optional
    ports:
      - 8096:8096
      # - 7359:7359/udp  # optional
      # - 1900:1900/udp  # optional
    devices:
      - /dev/dri:/dev/dri  # optional
      - /dev/vcsm:/dev/vcsm  # optional
      - /dev/vchiq:/dev/vchiq  # optional
      - /dev/video10:/dev/video10  # optional
      - /dev/video11:/dev/video11  # optional
      - /dev/video12:/dev/video12  # optional
    restart: unless-stopped
